### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by ycx974577817** [LiangLuDev/DevShapeUtils#1]
kotlin这样调用会报重载错误
DevShapeUtils.shape(DevShape.OVAL)
                .gradientLinear(DevShape.LEFT_RIGHT, "#A1C4FD", "#8FD3F4", "#58BFED")
                .into(tvBoy)

**Comment by LiangLuDev** [comment]
谢谢反馈。此库不支持kotlin，后面会考虑kotlin

**Comment by ycx974577817** [comment]
我看了一下,报错是因为gradientLinear方法第一个参数是String,后面的可变参数也是String,IDE无法判断引起的.

**Comment by LiangLuDev** [comment]
@ycx974577817 你好 具体你可以看https://github.com/LiangLuDev/DevShapeUtils/blob/HEAD/library/src/main/java/com/luliang/shapeutils/shape/DevShape.java 注释，kotlin应该是用不了的。
